[project]
name = "eggdishes-core"
version = "0.2.0"
description = "core module for eggdishes"
readme = "README.md"
dependencies = [
    "pluggy>=1.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
